version: "2.1"
services:
  courts-ms:
    build: .     
    healthcheck:
      interval: 30s
      timeout: 15s
      retries: 30
    ports:
      - "4005:4005"
    depends_on:
      courts-db:
        condition: service_healthy

  courts-db:
    image: mysql:5.7
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 30s
      timeout: 15s
      retries: 30
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: courts-db
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_HOST: courts-db
    ports:
      - "3306:3306"
