## Pull the mysql:5.7 image
FROM mysql:5.7

## The maintainer name and email
MAINTAINER David Hormaza <dehormazah@unal.edu.co>

# database = courts and password for root = 12345678
ENV MYSQL_DATABASE=courts_db \
    MYSQL_ROOT_PASSWORD=12345678
